/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.epam.training.fooddelivery.api;

import com.epam.training.fooddelivery.model.FoodModel;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-08-18T19:12:13.004527200+03:00[Europe/Minsk]")
@Validated
@Api(value = "foodservice", description = "the foodservice API")
public interface FoodserviceApi {

    /**
     * GET /foodservice/foods : List all foods
     * Show list of all foods available in foodservice
     *
     * @return A list of foods (status code 200)
     */
    @ApiOperation(value = "List all foods", nickname = "listAllFoods", notes = "Show list of all foods available in foodservice", response = FoodModel.class, responseContainer = "List", tags={ "food-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A list of foods", response = FoodModel.class, responseContainer = "List") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/foodservice/foods",
        produces = { "application/json" }
    )
    ResponseEntity<List<FoodModel>> listAllFoods();

}
